"""author things

Revision ID: 18656643a496
Revises: 311fb983b597
Create Date: 2022-01-14 08:59:02.034017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18656643a496'
down_revision = '311fb983b597'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('author_name', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'author_name')
    # ### end Alembic commands ###
