"""Add foreign key

Revision ID: 311fb983b597
Revises: 7a560db117a7
Create Date: 2022-01-14 08:56:29.297430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '311fb983b597'
down_revision = '7a560db117a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('author_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'books', 'users', ['author_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.drop_column('books', 'author_id')
    # ### end Alembic commands ###
